name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^6.5.7
  firebase_ai: ^3.15.0
  cloud_firestore: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: NanumBarunpen
      fonts:
        - asset: assets/fonts/NanumFontSetup_TTF_BARUNPEN/NanumBarunpenR.ttf
        - asset: assets/fonts/NanumFontSetup_TTF_BARUNPEN/NanumBarunpenB.ttf
          weight: 700
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumFontSetup_TTF_GOTHIC/NanumGothicLight.ttf
          weight: 300
        - asset: assets/fonts/NanumFontSetup_TTF_GOTHIC/NanumGothic.ttf
        - asset: assets/fonts/NanumFontSetup_TTF_GOTHIC/NanumGothicBold.ttf
          weight: 700
        - asset: assets/fonts/NanumFontSetup_TTF_GOTHIC/NanumGothicExtraBold.ttf
          weight: 800
    - family: NanumSquare
      fonts:
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquareL.ttf
          weight: 300
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquareR.ttf
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquareB.ttf
          weight: 700
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquareEB.ttf
          weight: 800
    - family: NanumSquare_ac
      fonts:
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquare_acL.ttf
          weight: 300
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquare_acR.ttf
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquare_acB.ttf
          weight: 700
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE/NanumSquare_acEB.ttf
          weight: 800
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE_ROUND/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE_ROUND/NanumSquareRoundR.ttf
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE_ROUND/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumFontSetup_TTF_SQUARE_ROUND/NanumSquareRoundEB.ttf
          weight: 800

